# Generated by Django 5.0 on 2023-12-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='')),
                ('nom', models.CharField(max_length=50)),
                ('narx', models.CharField(max_length=50)),
                ('brend', models.CharField(max_length=50)),
            ],
        ),
    ]
