# Generated by Django 5.0 on 2023-12-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0004_remove_asosiysahifa_brend'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoshqaMahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AsosiySahifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.asosiysahifa')),
            ],
        ),
        migrations.CreateModel(
            name='Soatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AsosiySahifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.asosiysahifa')),
            ],
        ),
        migrations.CreateModel(
            name='Telefonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AsosiySahifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.asosiysahifa')),
            ],
        ),
    ]
