# Generated by Django 5.0 on 2023-12-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0005_boshqamahsulotlar_soatlar_telefonlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSahifalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='')),
                ('nom', models.CharField(max_length=30)),
                ('matn', models.CharField(max_length=200)),
            ],
        ),
    ]
