# Generated by Django 5.0 on 2023-12-25 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0006_websahifalar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SahifaAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WebSahifalar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.websahifalar')),
            ],
        ),
    ]
