# Generated by Django 5.0 on 2023-12-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0007_sahifaabout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SahifaAbout',
        ),
    ]
