# Generated by Django 5.0 on 2023-12-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0008_delete_sahifaabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malumot', models.CharField(max_length=300)),
                ('AsosiySahifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.asosiysahifa')),
            ],
        ),
    ]
