# Generated by Django 5.0 on 2023-12-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0009_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='AsosiySahifa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='Asosiy.asosiysahifa'),
        ),
    ]
