# Generated by Django 5.0 on 2023-12-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0010_alter_productdetail_asosiysahifa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
