# Generated by Django 5.0 on 2024-01-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0015_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
